"""Engine adapters — each file is one search engine.

Importing this module triggers @register_engine on all adapters,
populating the global engine registry.
"""

from . import (
    abuseipdb,
    arxiv,
    brave,
    censys,
    crtsh,
    cve,
    dehashed,
    duckduckgo,
    epss,
    exploitdb,
    github,
    google,
    greynoise,
    hackernews,
    hibp,
    huggingface,
    intelx,
    internetarchive,
    mitreattack,
    nvd,
    openalex,
    otx,
    reddit,
    semanticscholar,
    shodan,
    stackexchange,
    urlhaus,
    virustotal,
    vulncheck,
    wikipedia,
)

__all__ = [
    "abuseipdb",
    "arxiv",
    "brave",
    "censys",
    "crtsh",
    "cve",
    "dehashed",
    "duckduckgo",
    "epss",
    "exploitdb",
    "google",
    "github",
    "greynoise",
    "hackernews",
    "hibp",
    "huggingface",
    "internetarchive",
    "intelx",
    "mitreattack",
    "nvd",
    "openalex",
    "otx",
    "reddit",
    "semanticscholar",
    "shodan",
    "stackexchange",
    "urlhaus",
    "virustotal",
    "vulncheck",
    "wikipedia",
]
