apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: slopsearx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: slopsearx
  minReplicas: 3
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
